import {colours,flatten,mergeLive,leaderboard} from './live.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=s=>new Date(s).toLocaleString('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
let feed,rows=[],selected=null,arrivals=[],requestId=0,liveAt=null;
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(16000),cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
function render(){rows=leaderboard(feed,Number($('#window').value));selected=selected||rows.at(-1)?.id;
 const count=feed.snapshots.length,age=(Date.now()-Date.parse(feed.updated))/60000;
 $('#coverage').textContent=`${count} network observations · collection began ${stamp(feed.started)}`;
 $('#updated').textContent=`${liveAt?'Live service checked':'Last collected observation'} ${stamp(feed.updated)}`;
 $('#notice').textContent=count<8?'The collector has just started. These are real observations, but the history is still short; ratings will become more informative as it accumulates.':age>45?'The collected feed is over 45 minutes old. Its timestamp is shown; no observations have been invented.':'';
 $('#lines').innerHTML=rows.map((r,n)=>`<button class="line" data-id="${r.id}" style="--line:${colours[r.id]}" aria-pressed="${selected===r.id}" aria-label="${esc(r.name)}, Elo ${r.elo.toFixed(1)}, ${esc(r.status)}"><span class="rank">${String(n+1).padStart(2,'0')}</span><span class="line-name">${esc(r.name)}<small class="${r.severity<10?'bad':''}">${esc(r.status)}</small></span><span class="track"><span class="baseline"></span><span class="bar" style="width:${r.elo/3500*100}%"></span></span><span class="elo">${r.elo.toFixed(1)}</span></button>`).join('');
 for(const button of $('#lines').querySelectorAll('button'))button.onclick=()=>select(button.dataset.id);
 detail();window.__tfl={ready:true,feed,rows,liveAt,selected};
}
function detail(){const r=rows.find(r=>r.id===selected);if(!r)return;$('#detail').style.setProperty('--line',colours[r.id]);$('#line-title').textContent=r.name;$('#line-reason').textContent=r.reason||r.status;$('#line-stats').innerHTML=`<div><dt>reliability elo</dt><dd>${r.elo.toFixed(1)}</dd></div><div><dt>observations</dt><dd>${r.observations}</dd></div><div><dt>good service</dt><dd>${r.good===null?'—':(r.good*100).toFixed(0)+'%'}</dd></div>`;
 const h=r.history;if(h.length<2){$('#rating-chart').textContent='Rating history will appear after the next collected observation.';return;}
 const vals=[1500,...h.map(p=>p.elo)],min=Math.min(...vals)-2,max=Math.max(...vals)+2,points=vals.map((v,i)=>`${10+i/(vals.length-1)*360},${118-(v-min)/(max-min)*95}`).join(' ');
 $('#rating-chart').innerHTML=`<svg viewBox="0 0 380 140" role="img" aria-label="${esc(r.name)} rating over collected observations"><line x1="10" x2="370" y1="120" y2="120" stroke="#3c5262"/><polyline points="${points}" fill="none" stroke="${colours[r.id]}" stroke-width="3"/><text x="10" y="137" font-size="10" fill="#a0b5c4">${stamp(h[0].at)}</text><text x="370" y="137" text-anchor="end" font-size="10" fill="#a0b5c4">${stamp(h.at(-1).at)}</text></svg>`;
}
async function select(id){selected=id;render();const request=++requestId;$('#arrivals-note').textContent='Getting live arrival predictions…';$('#arrivals').replaceChildren();try{const data=await get(`https://api.tfl.gov.uk/Line/${encodeURIComponent(id)}/Arrivals`);if(request!==requestId)return;if(!Array.isArray(data))throw Error('Unexpected arrival response');arrivals=data;const stations=[...new Set(data.map(r=>r.stationName))].sort();$('#station').innerHTML=stations.map(s=>`<option>${esc(s)}</option>`).join('');$('#arrivals-note').textContent=`TfL predictions checked ${new Date().toLocaleTimeString('en-GB')}. Select a station.`;renderArrivals();}catch(e){if(request!==requestId)return;$('#station').innerHTML='<option>unavailable</option>';$('#arrivals-note').textContent='Live arrivals are unavailable right now. The observed line rating remains above.';}}
function renderArrivals(){const subset=arrivals.filter(a=>a.stationName===$('#station').value).sort((a,b)=>Date.parse(a.expectedArrival)-Date.parse(b.expectedArrival)).slice(0,8);$('#arrivals').innerHTML=subset.length?subset.map(a=>`<div class="arrival"><span>${esc(a.destinationName||a.towards||'destination pending')}<br><small>${esc(a.platformName||'')}</small></span><strong>${Math.max(0,Math.ceil((Date.parse(a.expectedArrival)-Date.now())/60000))} min</strong></div>`).join(''):'<p class="small">No predicted trains at this station.</p>';}
async function refresh(){const button=$('#refresh');button.disabled=true;$('#connection').textContent='checking TfL';try{try{const shared=await get('./data/network.json');if(!feed||Date.parse(shared.updated)>Date.parse(feed.snapshots.at(-1)?.at||0))feed=shared;else{const byBucket=new Map(feed.snapshots.map(s=>[Math.floor(Date.parse(s.at)/600000),s]));for(const snap of shared.snapshots)byBucket.set(Math.floor(Date.parse(snap.at)/600000),snap);feed={...feed,snapshots:[...byBucket.values()].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at))};}}catch{}const lines=flatten(await get('https://api.tfl.gov.uk/Line/Mode/tube/Status'));liveAt=new Date().toISOString();feed=mergeLive(feed||{snapshots:[],started:liveAt},lines,liveAt);$('#connection').textContent='live service connected';render();}catch(e){$('#connection').textContent=feed?'showing collected observations':'TfL unavailable';$('#notice').textContent=feed?'The direct TfL request failed. Showing the last collected observations with their timestamp.':'No live response or saved feed is available. Refresh to try again.';}finally{button.disabled=false;}}
$('#window').onchange=render;$('#refresh').onclick=refresh;$('#station').onchange=renderArrivals;
$('#download').onclick=()=>{if(!rows.length)return;const data=[['line','elo','observations','good_service_share','status','observed_at'],...rows.map(r=>[r.name,r.elo,r.observations,r.good,r.status,feed.updated])].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([data],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='tube-reliability.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
try{feed=await get('./data/network.json');render();$('#connection').textContent='collected history loaded';}catch{}
await refresh();if(rows.length)select(selected);
setInterval(()=>{if(!document.hidden)refresh();},60000);
